name: Release Commenter

on:
  release:
    types: [published]

jobs:
  release-commenter:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip-label: 'autorelease: tagged,dependencies,maintenance'
